version: '3.7'

services:
  mysql:
    image: 'mysql:8.0.28'
    environment:
      - 'MYSQL_DATABASE=docz'
      - 'MYSQL_ROOT_PASSWORD=123456'
      - 'MYSQL_ROOT_USER=root'
    ports:
      - '3306:3306'